name: BLOG

on:
  push:
    branches:
      - blog
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout hexo repo
        uses: actions/checkout@v2
        with:
          repository: oneforce/oneforce.github.io
          ref: hexo
          path: hexo

      - name: copy hexo file
        run: |
          cp -r hexo/* .

    #   # - name: Checkout deploy repo
    #   #   uses: actions/checkout@v2
    #   #   with:
    #   #     repository: ${{ env.DEPLOY_REPO }}
    #   #     ref: ${{ env.DEPLOY_BRANCH }}
    #   #     path: .deploy_git

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Configuration environment
        run: |
          sudo timedatectl set-timezone "Asia/Shanghai"

      - name: Install dependencies
        run: |
          npm install

      - name: Hexo generate
        run: |
          hexo cl
          hexo g

    # - name: push to origin master
    #   run: |
    #     echo start push
    #     cd ./public
    #     git init
    #     git config user.name "yourname"
    #     git config user.email "your email"
    #     git add .
    #     git commit -m "update"
    #     git push --force --quiet "https://${secrets.BLOG_GITHUB_TOKEN}@github.com/oneforce/oneforce.github.io.git" master:master