name: Saglow BLOG

on:
  push:
    branches:
      - blog
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout hexo repo
        uses: actions/checkout@v2
        with:
          repository: Saglow/saglow.github.io
          ref: hexo
          path: hexo

      - name: Checkout hexo repo
        uses: actions/checkout@v2
        with:
          repository: Saglow/saglow.github.io
          ref: master
          path: ./public

      - name: copy hexo file
        run: |
          cp -r hexo/* .

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Configuration environment
        run: |
          sudo timedatectl set-timezone "Asia/Shanghai"

      - name: Install dependencies
        run: |
          npm install

      - name: Hexo generate
        run: |
          npx hexo cl
          npx hexo g

      - name: push to origin master
        run: |
          echo start push
          cd ./public
          git config --global init.defaultBranch master
          git config --global user.name "fangyuhui"
          git config --global user.email "fangyuhui2001@gmail.com"
          git init .
          git add .
          git commit -m "update"
          # git push
          git push --force --quiet "https://${{secrets.BLOG_GITHUB_TOKEN}}@github.com/Saglow/saglow.github.io.git" master:master
